version: '3.3'
services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: template
      MYSQL_DATABASE: template
      MYSQL_USER: template
      MYSQL_PASSWORD: template
    ports:
    - "3306:3306"